logic_metadata = {
    "001_turnover_breach_lowerside_final": {
        "Exception Text": "Expected account annual turnover in KYC profile of a customer fed on a higher side, which did not commensurate with the overall profile of the customer & actual turnover in the account.",
        "Risk": "H",
        "Control Number": "117",
        "eAudit Head Name": "Exceptional Turnover Report",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Validate all cases of corporate customers from CBS as current account annual total turnovers as per KYC are not available in any report.",
    },
    "002_turnover_breach_upperside_final": {
        "Exception Text": "Actual accounts annual turnovers (p.a.) were found in excess of expected turnovers fed in KYC profiles of customers; however, review / updation of KYC profiles of such customers in light of CDD / EDD perspectives were not carried out till audit review date.",
        "Risk": "H",
        "Control Number": "9-27",
        "eAudit Head Name": "Exceptional Turnover Report",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Validate all cases of corporate customers from CBS as current account annual total turnovers as per KYC are not available in any report.",
    },
    "003_joint_name_misassignment": {
        "Exception Text": "Customer ID tagged with joint account was created in core banking system with name of joint account holders instead of name of account holder to whom such ID belongs.",
        "Risk": "M",
        "Control Number": "9-28",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "004_missing_joint_kyc_profiles": {
        "Exception Text": "Separate KYC Profiles of all joint account holders are not maintained.",
        "Risk": "H",
        "Control Number": "80",
        "eAudit Head Name": "CRP Profiling (Top 100 & Closed Accounts Data)",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "005_multiple_cifs_non_joint_account": {
        "Exception Text": "Multiple CIFs were found tagged with account of single customer [Non-Joint Account].",
        "Risk": "H",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "006_missing_purpose_of_account": {
        "Exception Text": "Purpose for opening of account was not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "94",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "007_occupation_purpose_mismatch": {
        "Exception Text": "Purpose for opening of accounts fed in KYC profiles of customers were found contradict with occupations of customers.",
        "Risk": "M",
        "Control Number": "9-34",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "008_pension_purpose_missing": {
        "Exception Text": "Purpose for opening of account was not fed as pension in pensioner's account marked as 'Pensioner' in core banking system.",
        "Risk": "M",
        "Control Number": "9-34",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "0",
        "Control Effectiveness": "",
        "Note": "Pension account marking need to checked on CBS.",
    },
    "009_business_salaried_profile_match": {
        "Exception Text": "Purpose for opening of AKK / Falah Business / Alfalah Islamic Business Way / CPA / Alfalah Islamic Business Way Payrol accounts were not fed as business & salaried respectively in KYC profiles of business & salaried persons.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Exclude those accounts were purpose for opening of AKK/CPA accounts were fed as business/salaried with incorrect spellings.",
    },
    "010_personal_fcy_business_purpose": {
        "Exception Text": "Purpose for opening of personal foreign currency account was fed as 'Business' instead of 'Saving' as personal FCY account cannot be used for business purpose.",
        "Risk": "M",
        "Control Number": "9-34",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "011_product_occupation_mismatch": {
        "Exception Text": "Account was opened in product type that was found irrelevant to occupation of a customer.",
        "Risk": "M",
        "Control Number": "2.4-110",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "012_unsc_screening_mismatch": {
        "Exception Text": "Account was screen out from list of proscribed individuals at the time of account opening however Account Screen out field was either left blank or fed as 'No' in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "110",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "013_missing_account_turnover_in_kyc": {
        "Exception Text": "Account annual turnovers were not fed in KYC profiles of customers.",
        "Risk": "H",
        "Control Number": "9-36",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "014_missing_monthly_turnover": {
        "Exception Text": "Account expected monthly credit turnovers were not fed in KYC profiles of customers.",
        "Risk": "H",
        "Control Number": "92",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "015_account_turnover_mismatch": {
        "Exception Text": "Account annual turnover fed as above 10M/50M however amount greater than 10M/50M was not specified in relevant field of KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-38",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "016_monthly_turnover_mismatch": {
        "Exception Text": "Account expected monthly credit turnover fed as above 10M/50M however amount greater than 10M/50M was not specified in relevant field of KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-40",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "017_turnover_contradiction": {
        "Exception Text": "Primary & Secondary account annual turnover fed in KYC profile of a customer was found contradictory with each other.",
        "Risk": "H",
        "Control Number": "9-37",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "018_monthly_turnover_contradiction": {
        "Exception Text": "Primary & Secondary account expected monthly credit turnover fed in KYC profile of a customer was found contradictory with each other.",
        "Risk": "H",
        "Control Number": "9-37",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account monthly turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "019_annual_turnover_contradiction": {
        "Exception Text": "Account annual turnover was fed as Above 10M/50M in KYC profile of a customer however amount less than or equal to 10M/50M was specified in relevant field.",
        "Risk": "H",
        "Control Number": "9-37",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "020_monthly_credit_turnover_contradiction": {
        "Exception Text": "Account expected monthly credit turnover was fed as Above 10M/50M in KYC profile of a customer however amount less than or equal to 10M/50M was specified in relevant field.",
        "Risk": "H",
        "Control Number": "9-37",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account monthly turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "021_account_annual_vs_monthly_turnover_contradiction": {
        "Exception Text": "Account annual turnovers fed in KYC profiles of customers were found equivalent to or less than account expected monthly credit turnovers.",
        "Risk": "H",
        "Control Number": "106",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "022_account_vs_business_turnover_contradiction": {
        "Exception Text": "Account annual turnovers were significantly lower than business turnovers fed in KYC profiles of business customers.",
        "Risk": "H",
        "Control Number": "106",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual turnovers of corporate customers must be validated from CBS as the same extracted from report generated on audit cut-off date and not reflect subsequent changes.",
    },
    "023_turnover_exceeds_salary_for_salaried_profiles": {
        "Exception Text": "Account annual turnovers were found higher than salary & other incomes fed in KYC profiles of salaried / housewife / retired / students.",
        "Risk": "H",
        "Control Number": "9-43",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "024_actual_credit_turnover_exceeds_income_for_nonbusiness_profiles": {
        "Exception Text": "Account annual actual credit turnovers were significantly higher in comparison with salary and other incomes fed in KYC profiles of salaried / housewife / retired / students.",
        "Risk": "H",
        "Control Number": "2.4-105",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual actual credit turnovers should be validated from CBS.",
    },
    "025_actual_credit_turnover_exceeds_business_turnover": {
        "Exception Text": "Account annual actual credit turnovers were significantly higher in comparison with business turnovers fed in KYC profiles of business customers.",
        "Risk": "H",
        "Control Number": "2.4-104",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual actual credit turnovers should be validated from CBS.",
    },
    "026_missing_source_of_income": {
        "Exception Text": "Sources of incomes were not fed in KYC profiles of customers.",
        "Risk": "M",
        "Control Number": "96",
        "eAudit Head Name": "KYC-Old Accounts - Individual, Housewife & Similar",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "027_soi_occupation_contradiction": {
        "Exception Text": "Source of income fed in KYC profile of a customer was found contradictory with occupation of a customer.",
        "Risk": "H",
        "Control Number": "2.4-107",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "028_staff_account_not_salaried": {
        "Exception Text": "Staff Account was not tagged with occupation salaried in KYC profile.",
        "Risk": "H",
        "Control Number": "128",
        "eAudit Head Name": "KYC-Old Accounts - Individual, Housewife & Similar",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "029_sole_proprietor_not_business": {
        "Exception Text": "Sole Proprietor account was not tagged with occupation business in KYC profile.",
        "Risk": "H",
        "Control Number": "128",
        "eAudit Head Name": "KYC-Old Accounts - Individual, Housewife & Similar",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "030_missing_expected_credit_txns": {
        "Exception Text": "Number of expected monthly credit transactions was not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "9-44",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "031_missing_dominant_deposit_mode": {
        "Exception Text": "Dominant modes of deposits were not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "9-45",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "032_missing_dominant_withdrawal_mode": {
        "Exception Text": "Dominant modes of withdrawals were not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "9-45",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "033_cash_only_profile_vs_actual_ft": {
        "Exception Text": "Dominant mode of transactions fed in KYC profile of a customer was only cash however in actual fund transfer transactions were also observed / executed in account during audit period.",
        "Risk": "M",
        "Control Number": "2.4-108",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "In order to derive authentic results, desired columns of FT KYC Report must be pasted in its respective tab after removal of all duplications.",
    },
    "034_inward_remittance_missing_geography": {
        "Exception Text": "Inward foreign remittance was fed as dominant mode of deposit in KYC profile of a customer however expected international geographies were not updated accordingly.",
        "Risk": "H",
        "Control Number": "112",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "035_cash_mode_in_fcy_without_sbp_approval": {
        "Exception Text": "Dominant mode of transactions was fed as 'Cash' in a FCY entity account without having approval of SBP.",
        "Risk": "M",
        "Control Number": "9-32",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "SBP Approval must be checked on Rosetta Workflow/DMS/Rapid Portal/obtained from branch before finalizing exception.",
    },
    "036_import_export_missing_geography": {
        "Exception Text": "Nature of business was fed as 'Import & Export' in KYC profile of a customer however expected international geographies were not updated accordingly.",
        "Risk": "H",
        "Control Number": "81",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "037_missing_other_bank_account_disclosure": {
        "Exception Text": "Details of accounts maintained in other banks were neither enquired nor captured by branch in KYC profile of a high Risk customer.",
        "Risk": "M",
        "Control Number": "9-77",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Other bank account details of 01 account would appear in table of exception however the details of all other bank accounts should be checked from AAU RTGS Outflow Report [A001] and incorporate manually in table of exception.",
    },
    "038_missing_guardian_name_for_minor": {
        "Exception Text": "Name of a guardian was not fed in KYC profile of a minor.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "039_missing_guardian_cnic_for_minor": {
        "Exception Text": "CNIC Number of a guardian was not fed in KYC profile of a minor.",
        "Risk": "M",
        "Control Number": "9-46",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "040_missing_guardian_relationship_for_minor": {
        "Exception Text": "Relationship of a guardian with minor was not fed in KYC profile of a minor.",
        "Risk": "M",
        "Control Number": "9-47",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "041_missing_sole_proprietor_name": {
        "Exception Text": "Name of a sole proprietor was not fed in KYC profile of a sole proprietor customer.",
        "Risk": "M",
        "Control Number": "9-52",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "042_missing_name_of_business": {
        "Exception Text": "Names of businesses were not fed in KYC profiles of business individuals.",
        "Risk": "H",
        "Control Number": "9-53",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "043_business_name_for_non_business_customer": {
        "Exception Text": "Name of a business was fed in KYC profile of a non-business customer.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "044_missing_nature_of_business": {
        "Exception Text": "Nature of businesses were not fed in KYC profiles of business customers.",
        "Risk": "H",
        "Control Number": "9-64",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "045_nature_of_business_for_non_business_customer": {
        "Exception Text": "Nature of business was fed in KYC profile of a non-business customer.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "046_generalized_nature_of_business_for_business_customer": {
        "Exception Text": "Nature of business was not explicitly defined instead generalized term i.e. Trading / Import & Export etc. was fed in KYC profile of a business customer.",
        "Risk": "M",
        "Control Number": "91",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "047_missing_ownership_status_for_business_individual": {
        "Exception Text": "Ownership status were not fed in KYC profiles of business individual customers.",
        "Risk": "M",
        "Control Number": "9-65",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "048_misclassified_ownership_status_for_business_individual": {
        "Exception Text": "Ownership status was wrongly fed in KYC profile of a business individual as 'Sole Proprietor / Owner' whereas in actual account holder is a partner or director of such firm / entity.",
        "Risk": "M",
        "Control Number": "9-66",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Booked exception after validate that business individual is a partner or director in partnership/private limited company check from SS Card/Partnership Mandate/AOF, further business address must be same in personal and corporate company accounts.",
    },
    "049_missing_employer_name_for_salaried_individual": {
        "Exception Text": "Name of an employer was not fed in KYC profile of a salaried individual.",
        "Risk": "H",
        "Control Number": "9-55",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "050_missing_bank_alfalah_employer_for_bank_staff": {
        "Exception Text": "Name of an employer was not fed as 'Bank Alfalah Ltd.' in KYC profile of a bank staff.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "051_missing_title_or_position_for_salaried_individuals": {
        "Exception Text": "Title / Positions were not fed in KYC profiles of salaried individuals.",
        "Risk": "H",
        "Control Number": "9-56",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "052_missing_employment_start_date_for_salaried_individuals": {
        "Exception Text": "Dates of commencement of employments were not fed in KYC profiles of salaried individuals.",
        "Risk": "M",
        "Control Number": "9-57",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "053_missing_employment_status_for_salaried_individuals": {
        "Exception Text": "Status of employments [Permanent / Contractual / 3rd Party Contract] were not fed in KYC profiles of salaried individuals.",
        "Risk": "M",
        "Control Number": "9-59",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "054_employer_name_fed_for_non_salaried_individuals": {
        "Exception Text": "Name of an employer was fed in KYC profile of a non-salaried individual.",
        "Risk": "M",
        "Control Number": "9-60",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "055_position_fed_for_non_salaried_individuals": {
        "Exception Text": "Title / Position was fed in KYC profile of a non-salaried individual.",
        "Risk": "M",
        "Control Number": "9-60",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "056_employment_status_fed_for_non_salaried_individuals": {
        "Exception Text": "Status of an employment was fed in KYC profile of a non-salaried individual.",
        "Risk": "M",
        "Control Number": "9-60",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "057_salary_other_income_missing_for_expected_profiles": {
        "Exception Text": "Salary & Other Incomes were not fed in KYC profiles of salaried, retired, housewife, students.",
        "Risk": "H",
        "Control Number": "9-61",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "058_salary_other_income_fed_for_business_without_source": {
        "Exception Text": "Salary & Other Income was fed in KYC profile of a business customer without mentioning source of other income.",
        "Risk": "H",
        "Control Number": "118",
        "eAudit Head Name": "KYC-Old Accounts - Individual, Housewife & Similar",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "059_investment_missing_for_business_profiles": {
        "Exception Text": "Business investments were not fed in KYC profiles of business customers.",
        "Risk": "M",
        "Control Number": "9-67",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "060_business_turnover_missing_for_business_profiles": {
        "Exception Text": "Business turnovers were not fed in KYC profiles of business customers.",
        "Risk": "H",
        "Control Number": "9-68",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "061_investment_fed_for_non_business_profiles": {
        "Exception Text": "Business investment was fed in KYC profile of a non-business customer.",
        "Risk": "M",
        "Control Number": "2.4-102",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "062_turnover_fed_for_non_business_profiles": {
        "Exception Text": "Business turnover was fed in KYC profile of a non-business customer.",
        "Risk": "M",
        "Control Number": "2.4-102",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "063_missing_occupation_in_kyc_profiles": {
        "Exception Text": "Customers were not tagged with any occupation in KYC profiles.",
        "Risk": "H",
        "Control Number": "9-33",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "064_missing_expected_local_geography": {
        "Exception Text": "Expected local geographies for transactions were not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "111",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "065_missing_expected_international_geography": {
        "Exception Text": "Expected international geographies for transactions were not fed in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "111",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "066_sanctioned_jurisdiction_in_expected_international_geography": {
        "Exception Text": "Name of a sanctioned / banned international jurisdiction was fed as expected international geography for transactions in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-76",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Names of all international jurisdictions as per KYC profile are mentioned in 4th column of table of this exception so auditor needs to mention/clarify name of sanctioned international jurisdiction validated from latest compliance operational manual issued by SP&P.",
    },
    "067_expected_counterparties_missing_for_business_customers": {
        "Exception Text": "Expected type of counter parties were not fed in KYC profiles of business customers.",
        "Risk": "M",
        "Control Number": "111",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "068_pep_status_blank_in_kyc_profile": {
        "Exception Text": "PEP status of customer was found blank in KYC profile.",
        "Risk": "H",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "069_contradictory_pep_status_across_accounts": {
        "Exception Text": "Contradiction was observed in KYC profiles of multiple accounts of same customer [tagged with different customer IDs] where PEP status of a customer was marked as 'Yes' in one account and marked as 'No' in other account.",
        "Risk": "H",
        "Control Number": "9-51",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "070_pep_approval_missing_for_pep_customers": {
        "Exception Text": "PEP approval field was fed as No or left blank in KYC profile of a PEP customer.",
        "Risk": "H",
        "Control Number": "2.4-106",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "071_pep_customer_not_marked_high_risk": {
        "Exception Text": "PEP Customer was not marked as 'High' Risk in his/her KYC profile.",
        "Risk": "H",
        "Control Number": "2.3-232",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "072_risk_level_blank_in_kyc_profile": {
        "Exception Text": "Risk level of a customer was found blank in KYC profile.",
        "Risk": "H",
        "Control Number": "113",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "073_ecrp_not_available_in_core_banking": {
        "Exception Text": "eCRP of a customer was not made / available in core banking system.",
        "Risk": "H",
        "Control Number": "3.3-211",
        "eAudit Head Name": "CRP Profiling (Top 100 & Closed Accounts Data)",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "074_edd_not_made_for_high_risk_customers": {
        "Exception Text": "Enhance Due Diligence (EDD) of a high Risk customer was not made / available in core banking system.",
        "Risk": "H",
        "Control Number": "98",
        "eAudit Head Name": "CRP Profiling (Top 100 & Closed Accounts Data)",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes. Further check availability of EDD forms either available with branch or on Rosetta workflow and results should be booked accordingly in the exception.",
    },
    "075_incorporation_date_post_account_opening": {
        "Exception Text": "Date of incorporation of business fed in KYC profile of a business entity was found post to date of account opening.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "076_high_risk_pep_approval_check": {
        "Exception Text": "High Risk approval was left blank or marked as 'No' in KYC profile of a high Risk customer.",
        "Risk": "M",
        "Control Number": "9-75",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "077_blank_kyc_review_date": {
        "Exception Text": "KYC review date was found blank in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "2.1-234",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "078_kyc_review_frequency_breach": {
        "Exception Text": "KYC profile of a customer was not reviewed by branch within prescribed frequency. [High Risk: 01 Year, Medium Risk: 03 Years & Low Risk: 05 Years]",
        "Risk": "H",
        "Control Number": "3.3-230",
        "eAudit Head Name": "KYC-Old Accounts - High Turnover",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "079_customer_profile_snapshot_missing": {
        "Exception Text": "Customer Profile (Snapshot) was left blank in KYC profile of a customer.",
        "Risk": "M",
        "Control Number": "121",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "080_resigned_bank_staff_profile_not_updated": {
        "Exception Text": "KYC profile of a resigned bank staff was not updated with respect to his/her current designation, employer & professions.",
        "Risk": "M",
        "Control Number": "9-35",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "081_business_info_missing_for_atl_registered_individuals": {
        "Exception Text": "Different business were found registered in FBR on names of non-business individuals where business information was not enquired and captured in KYC profiles of customers that shows lack of CDD / EDD measures taken by branch either at the time of account opening or subsequently while performing periodic KYC reviews.",
        "Risk": "M",
        "Control Number": "2.1-233",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "FBR record need to be validated from FBR ATL or Portal as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes, further exclude all cases where name of account holder is appearing as a business in FBR record. Also exclude those cases where information of business was captured by branch in KYC snapshots.",
    },
    "082_employer_name_matches_atl_business": {
        "Exception Text": "Business registered in FBR on name of a salaried individual exactly match with name of an employer fed in KYC profile of a salaried individual that depicts salaried account was opened by employer through concealment of facts/actual identity.",
        "Risk": "H",
        "Control Number": "9-62",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "FBR record need to be validated from FBR ATL or Portal as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes, further address of employer as per bank record (if available) must be identical with the address of employer as per FBR record. Also check occupation of customer as per AOF, Search other accounts maintained by account holder in BAFL through advance customer search, Check their SS Cards, AOF and also check changes made in KYC profiles and total turnover / transaction pattern of account.",
    },
    "083_high_turnover_mismatch_with_declared_profile": {
        "Exception Text": "High turnover / business transactions were observed in account of a salaried / retired / housewife / student that was not match with disclosed profile of an account holder.",
        "Risk": "H",
        "Control Number": "89",
        "eAudit Head Name": "KYC-Old Accounts - Individual, Housewife & Similar",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account actual annual total turnovers and business transactions should be validated through CBS.",
    },
    "084_personal_fcy_used_for_business": {
        "Exception Text": "Personal foreign currency account was used by an account holder for business / commercial purposes in violation of Compliance Operational Manual.",
        "Risk": "H",
        "Control Number": "122",
        "eAudit Head Name": "KYC-Old Accounts - High Turnover",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "In order to derive authentic results, desired columns of FT KYC Report must be pasted in its respective tab after removal of all duplications.",
    },
    "085_personal_pkr_used_for_business": {
        "Exception Text": "Personal local currency account was used by an account holder for business / commercial purpose so that annual actual credit turnover of an account exceeds Rs. 450M.",
        "Risk": "H",
        "Control Number": "2.3-236",
        "eAudit Head Name": "KYC-Old Accounts - High Turnover",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "086_aggregate_personal_pkr_misuse": {
        "Exception Text": "Multiple personal local currency accounts were used by an account holder for business / commercial purpose in such a way that aggregate annual actual credit turnovers of all accounts exceeds Rs. 450M.",
        "Risk": "H",
        "Control Number": "9-73",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Account annual actual credit turnovers should be validated through CBS. Further the exception uploaded in e audit after sorting on CNIC number column.",
    },
    "087_multi_account_business_use_violation": {
        "Exception Text": "Multiple personal local currency accounts were used by an account holder for business / commercial purpose instead of using only one personal account for business purpose in violation of Compliance Operational Manual.",
        "Risk": "H",
        "Control Number": "2.4-115",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "In order to derive authentic results, desired columns of FT KYC Report must be pasted in its respective tab after removal of all duplications. Further the exception uploaded in e audit after sorting on CNIC number column.",
    },
    "088_personal_used_despite_company_account": {
        "Exception Text": "Personal local currency account was used by an account holder for business / commercial purpose despite availability of company account(s) in bank / branch.",
        "Risk": "H",
        "Control Number": "9-72",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "In order to derive authentic results, desired columns of FT KYC Report must be pasted in its respective tab after removal of all duplications. Further the exception uploaded in e audit after sorting on CNIC number column.",
    },
    "089_missing_director_partner_info": {
        "Exception Text": "Name & CNIC Numbers of directors / partners of a corporate customer was not fed in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-74",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "090_wrong_sole_proprietor_flag": {
        "Exception Text": "Ownership status was wrongly fed in KYC profile of a business individual customer as 'Sole Proprietor' whereas in actual account holder is a partner of such firm / entity as per his / her FBR record.",
        "Risk": "M",
        "Control Number": "9-66",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "FBR record need to be validated from FBR ATL or Portal as the report from which results derived was generated on audit cut",
    },
    "091_company_account_wrongly_flagged_as_sole_proprietor": {
        "Exception Text": "A company account was opened in sole proprietorship category rather than partnership category whereas account holder is a partner of such entity as per his/her FBR record.",
        "Risk": "H",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "FBR record need to be validated from FBR ATL or Portal as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes, further address of business as per bank record and FBR must be identical with each other.",
    },
    "092_missing_fund_provider_for_housewife_student": {
        "Exception Text": "Details of fund provider was not fed in core banking system in case of a Housewife / Student.",
        "Risk": "M",
        "Control Number": "2.4-112",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "093_invalid_fund_provider_for_business_salaried_landlord": {
        "Exception Text": "Details of fund provider was fed in an account of business / salaried / landlord customer.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "094_kyc_ecrp_Risk_mismatch": {
        "Exception Text": "Risk level of a customer as per eCRP was not matched with Risk level fed in his/her KYC profile.",
        "Risk": "H",
        "Control Number": "3.3-210",
        "eAudit Head Name": "CRP Profiling (Top 100 & Closed Accounts Data)",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Derived Result(s) must be validated from CBS as the report from which results derived was generated on audit cut-off date and not reflect subsequent changes.",
    },
    "095_non_numeric_turnover_flag": {
        "Exception Text": "Non-numeric account annual turnover was fed in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-39",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "096_non_numeric_monthly_turnover_flag": {
        "Exception Text": "Non-numeric account expected monthly credit turnover was fed in KYC profile of a customer.",
        "Risk": "H",
        "Control Number": "9-41",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "097_non_numeric_income_for_salaried_housewife_retired_student": {
        "Exception Text": "Non-numeric salary and other income was fed in KYC profile of a salaried / housewife / retired / student.",
        "Risk": "H",
        "Control Number": "9-78",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "098_non_numeric_business_investment_flag": {
        "Exception Text": "Non-numeric business investment was fed in KYC profile of a business customer.",
        "Risk": "M",
        "Control Number": "9-79",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "099_non_numeric_business_turnover_flag": {
        "Exception Text": "Non-numeric business turnover was fed in KYC profile of a business customer.",
        "Risk": "H",
        "Control Number": "9-80",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "100_conflicted_sole_proprietorship_flag": {
        "Exception Text": "Accounts having conflicted ownership status were found opened in the branch where different individuals were claiming the identical / same businesses of Sole Proprietorship as their source of income in contradiction to fact that multiple persons cannot become sole proprietor of same business.",
        "Risk": "H",
        "Control Number": "9-54",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "Cases reported should be checked for same addresses/ same signatures/ FBR records and in case same addresses/ FBR records exception with the recommendation [i.e. Branch is being advised to review the entire transactional activity / relationship of all the accounts from AML/ CFT perspective & investigate the other points of suspicion / concerns from the customer in light of the branch review along with above audit observations, and decide fate of the case on merit basis by following guidelines given in the Compliance Circular Ref: OPRN-645- COMP-1467-2019. Based on the above, if first line suspicion is formed, branch will be required to report the same as internal STR to the Compliance Division on immediate basis. should be booked and in case of identification of same signatures exceptions related to benami account should be finalized. Business address of all identified accounts must be validated from CBS/AOF and booked exception if all are identical. Also check accounts from benami aspect like signature on SS cards, CNIC, FBR Record, NOK, Advance Customer Search & etc.",
    },
    "101_employment_date_for_non_salaried_flag": {
        "Exception Text": "Date of commencement of an employment was fed in KYC profile of a non-salaried individual.",
        "Risk": "M",
        "Control Number": "9-60",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "102_understated_monthly_credit_transactions_flag": {
        "Exception Text": "Number of expected monthly credit transactions fed in KYC profiles of customers were significantly contradicts with actual average number of monthly credit transactions executed in accounts during audit period.",
        "Risk": "M",
        "Control Number": "9-44",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "103_ownership_status_for_non_business_flag": {
        "Exception Text": "Ownership status was fed in KYC profile of a non-business customer.",
        "Risk": "M",
        "Control Number": "Not Available",
        "eAudit Head Name": "Not Available",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "104_savings_purpose_for_business_account_flag": {
        "Exception Text": "Purpose for opening of account was fed as 'Savings' in KYC profile of a business customer whereas account was used for business transactions.",
        "Risk": "H",
        "Control Number": "116",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "In order to derive authentic results, desired columns of FT KYC Report must be pasted in its respective tab after removal of all duplications.",
    },
    "105_multiple_personal_accounts_with_business_purpose": {
        "Exception Text": "Purpose of accounts were fed in KYC profile as 'Business' in multiple personal accounts of same account holder in violation of instructions i.e., 'Multiple Personal Accounts are not allowed to use for business transactions'.",
        "Risk": "M",
        "Control Number": "9-34",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "106_missing_incorporation_date_for_business_entities": {
        "Exception Text": "Date of incorporation of businesses were not fed in KYC profiles of business entities.",
        "Risk": "M",
        "Control Number": "9-63",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
    "107_incor_date_fed_for_non_bus_indi": {
        "Exception Text": "Date of incorporation of business was fed in KYC profile of a non-business individual.",
        "Risk": "M",
        "Control Number": "252-90",
        "eAudit Head Name": "KYC-New Accounts",
        "Instances": "",
        "Control Effectiveness": "",
        "Note": "-",
    },
}
